### ISSUE TITLE
Unable to complete OAuth token exchange portion of authorization

### ISSUE THREAD

**Issue by vinniefranco** [andrewhao/ueberauth_strava#1]
Running into an issue with the token exchange portion of authenticating. Error as follows

```key :access_token not found in: %OAuth2.Client{authorize_url: "https://www.strava.com/oauth/authorize", client_id: "<<client_id>>", client_secret: "<<secret>>", headers: [], params: %{}, redirect_uri: "http://localhost:4000/auth/strava/callback", site: "https://www.strava.com/", strategy: Ueberauth.Strategy.Strava.OAuth, token: %OAuth2.AccessToken{access_token: nil, expires_at: nil, other_params: %{"errors" => [%{"code" => "invalid", "field" => "", "resource" => "Application"}], "message" => "Authorization Error"}, refresh_token: nil, token_type: "Bearer"}, token_method: :post, token_url: "https://www.strava.com/oauth/token"}```

I've verified that the code is in fact returned from the authorization route, so there's something weird with the hand off to the token route

**Comment by andrewhao** [comment]
Hi @vinniefranco - I'll investigate later this weekend. May I ask what context you're encountering this issue with, and the versions of `ueberauth` you're using?

**Comment by vinniefranco** [comment]
Running latest version of ueberauth, with ueberauth example app

**Comment by vinniefranco** [comment]
If I manually merge the client_id, and client_secret in `get_token!` then it works

**Comment by andrewhao** [comment]
Sorry for the late reply, @vinniefranco and thanks for doing the legwork on this. I'll check it out and merge when it looks good. Do you need a version bump from me?
